## Numpy Array Operations Indexing and Slicing

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ",arr[2:7])
print("Basic Slicing with gaps: ",arr[1:8:2])
print("Positive Indexing: ",arr[5])
print("Negative Indexing: ",arr[-3])

Basic Slicing:  [3 4 5 6 7]
Basic Slicing with gaps:  [2 4 6 8]
Positive Indexing:  6
Negative Indexing:  8


In [7]:
array2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element: " , array2d[1,2])
print("Specific Row: ",array2d[2])

Specific Element:  6
Specific Row:  [7 8 9]


## SORTING

In [17]:
unsorted = np.array([3,8,-9,100,14,36,0])
# np.sort(unsorted)    #This wont work as numpy returns updated copy of array not changes current array 
# print(unsorted)
sorted = np.sort(unsorted)
print(sorted)

## Custom Sort  --- row wise and column wise dono ho sakti he 
array2d = np.array([[3,1],[1,2],[2,3]])
print("Sorted array column wise: " , np.sort(array2d , axis = 0))
print("Sorted array row wise: ",np.sort(array2d , axis = 1))

# To sort complete array 
sorted_arr = np.sort(array2d, axis=None)   # sorts entire array
print("Sorted but flattens: ",sorted_arr)

final_sorted_arr = sorted_arr.reshape(3,2)
print("Resize it to get final array\n" , final_sorted_arr)

[ -9   0   3   8  14  36 100]
Sorted array column wise:  [[1 1]
 [2 2]
 [3 3]]
Sorted array row wise:  [[1 3]
 [1 2]
 [2 3]]
Sorted but flattens:  [1 1 2 2 3 3]
Resize it to get final array
 [[1 1]
 [2 2]
 [3 3]]


### Filters

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
evennum = arr[arr%2 == 0]  #masking is these 
print(evennum)

[ 2  4  6  8 10]


### Filter with Mask

In [25]:
mask = arr > 5
print("Numbers greater than 5: ", arr[mask]) 

arr = np.array([6,9,10,3,3,3])   ## works for sorted and unsorted both the arrays 
mask = arr > 6
print("Numbers greater than 5: ", arr[mask])

Numbers greater than 5:  [ 6  9 10]
Numbers greater than 5:  [ 9 10]


### Fancy Indexing vs np.where()

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
indexes = [0,3,9]
print(arr[indexes])

condition = np.where(arr > 4)
print(condition)
print("Numbers greater than 4: " , arr[condition])

[ 1  4 10]
(array([4, 5, 6, 7, 8, 9]),)
Numbers greater than 4:  [ 5  6  7  8  9 10]


In [37]:
condition_array = np.where(arr > 3)    #output >> (array([3, 4, 5, 6, 7, 8, 9]),)   to avoid these we have to provide multiple consitios 
print(condition_array)

condition_array = np.where(arr > 3 , arr*2 ,  arr)   # first is condition second is what to do if condition is true and third is the array name on which we are pergorming the operatons 
print(condition_array)

##  if arr[i] > 3  
    #     arr[i] = arr[i] * 2
    # else 
    #     arr[i] = arr[i]
## Remember its nit filter at all its just for confitoon fillling the numbers 


(array([3, 4, 5, 6, 7, 8, 9]),)
[ 1  2  3  8 10 12 14 16 18 20]


### Adding and Removing The data 

In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = arr1 + arr2   # this will just add the array elements
print(arr3)

# Merging the 2 arrays 
arr3 = np.concatenate((arr1 , arr2))
print(arr3)

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility --- just array checks 

In [51]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([1,2,3,4])

print("arr1 and arr2 are of the same dimensions: " , arr1.shape == arr2.shape)
print("arr1 and arr2 are of the same dimensions: " , arr1.shape == arr3.shape)

print("arr1 and arr2 are of the same dimensions: " , arr1 == arr2)   # here retrns true at the index wheere wlwments are same else false
arr2[2] = 4
print("arr1 and arr2 are of the same dimensions: " , arr1 == arr2)
# print("arr1 and arr2 are of the same dimensions: " , arr1 == arr3)   # Not for diff shapes so gives error 

arr1 and arr2 are of the same dimensions:  True
arr1 and arr2 are of the same dimensions:  False
arr1 and arr2 are of the same dimensions:  [ True  True  True]
arr1 and arr2 are of the same dimensions:  [ True  True False]


In [55]:
original = np.array([[1,2] , [3,4]])
newrow = np.array([6,8])
updated = np.vstack((original , newrow))
print("Original: " , original)
print("Updated: " , updated)

original = np.array([[1,2] , [3,4]])
newcol = np.array([[6] , [8]])
updated = np.hstack((original , newcol))
print("Original: " , original)
print("Updated: " , updated)

Original:  [[1 2]
 [3 4]]
Updated:  [[1 2]
 [3 4]
 [6 8]]
Original:  [[1 2]
 [3 4]]
Updated:  [[1 2 6]
 [3 4 8]]


In [62]:
#Deletion of the elemenst 
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr , 2)
print(deleted)
deleted = np.delete(arr,[1,2])
print(deleted)

print("--------------------------")
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# delete 2nd row (index 1)
new_arr = np.delete(arr, 1, axis=0)
print("New 2d array after 1st row deletion: ",new_arr)

new_arr = np.delete(arr, 2 , axis=1)     # delete column at index 1
print("New 2d array after 2nd column deletion: ",new_arr)

[1 2 4 5 6]
[1 4 5 6]
--------------------------
New 2d array after 1st row deletion:  [[1 2 3]
 [7 8 9]]
New 2d array after 2nd column deletion:  [[1 2]
 [4 5]
 [7 8]]
