## Numpy array and basics and learning numpy with chai aur code

In [2]:
import numpy as np

### creating array from the list

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)

brr = np.array([[1,2,3] , [4,5,6],[7,8,9]])
print(brr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs Numpy array 

In [9]:
py_list = [1,2,3]
print("Python list Multiplication: ", py_list * 2)  # length wise multiplication i,e repeying same list n times 

np_array = np.array([1,2,3])
print("Numpy array Multiplication: ",np_array * 2)    #elements wiise multiplication

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Numpy array Multiplication:  [2 4 6]


In [12]:
import time
start = time.time()
pylist = [i*2 for i in range(100000)]
print("Time required: " , time.time() - start)

start = time.time()
nparr = np.arange(100000) * 2
print("Time required: " , time.time() - start)

Time required:  0.0035986900329589844
Time required:  0.0009310245513916016


### Creating Array from the Scratch

In [21]:
zeros = np.zeros((3,4))
print(zeros) 

ones = np.ones((2,3))
print(ones)

constants = np.full((2,2) , 7)    #to create array with k in it 
print(constants)

rand = np.random.random((3,3))
print(rand)

sequence = np.arange(0,10,2)   # start , end , gap
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.03085481 0.42655698 0.88677571]
 [0.64969391 0.25887405 0.02226244]
 [0.69943034 0.12856742 0.14102822]]
[0 2 4 6 8]


### Vector Matrix and Tensor

In [29]:
vector = np.array([1,2,3,4])     #1-d array
print("Vector\n" , vector)

matrix = np.array([[1,2,3] , [4,5,6]])   #2-d array
print("Matrix\n" ,matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,9],[10,11]]])  #3-d array and more dimensionals all are tensors
print("Tensor\n" ,tensor)

Vector
 [1 2 3 4]
Matrix
 [[1 2 3]
 [4 5 6]]
Tensor
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 8  9]
  [10 11]]]


### Array Properties >>> 
- no issue if u keep data of differ datatype 
- but to optimize processing its prefer to have all emelemts with same datatypes 

In [31]:
arr = np.array([[1,2,3] , [4,5,6]])
print("Shape: ", arr.shape)    #m x n
print("Dimension: ", arr.ndim)   # 1d 2d or 3d and more
print("Size: ", arr.size)   # Total elements here 
print("Datatype: ",arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
Datatype:  int64


In [33]:
arr = np.array([[1,2,3] , [4,5,"om"]]) 
print("Datatype: ",arr.dtype)

arr = np.array([[1,2,3] , [4,5,3.8]])
print("Datatype: ",arr.dtype)

Datatype:  <U21
Datatype:  float64


### Array reshaping 

In [42]:
arr = np.arange(12)
print("Original Array: ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array: " , reshaped)

# reshaped = arr.reshape((3,3))     #This gives error as total elements should be matched before and after 
# print("Reshaped Array: " , reshaped)

flattened = reshaped.flatten()
print("Flatten Array: " , flattened)

#ravel returns view instead of the copy 
reveled = reshaped.ravel()
print("Raveled Array: ", reveled)

# Transpose of the matrixes 
print("Array: " , reshaped)
transpose = reshaped.transpose()
print("Transposed Array: " , transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed Array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
